name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  code-quality:
    name: "Code Quality"
    uses: ./.github/workflows/quality.yml
    secrets: inherit

  documentation:
    name: "Documentation"
    uses: ./.github/workflows/docs.yml
    secrets: inherit

  unit-tests:
    name: "Unit Tests"
    needs: [code-quality, documentation]
    uses: ./.github/workflows/test-unit.yml
    secrets: inherit

  integration-tests:
    name: "Integration Tests"
    needs: [code-quality, documentation]
    uses: ./.github/workflows/test-integration.yml
    secrets: inherit

  live-tests:
    name: "Live Tests"
    needs: [code-quality, documentation]
    uses: ./.github/workflows/test-live.yml
    secrets: inherit

  sonarcloud:
    name: "SonarCloud Analysis"
    if: always()
    needs: [unit-tests, integration-tests, live-tests]
    uses: ./.github/workflows/sonarqube.yml
    secrets: inherit
    with:
      unit-coverage-artifact: "unit-tests-coverage"
      integration-coverage-artifact: "integration-tests-coverage"
      live-coverage-artifact: "live-tests-coverage"
