name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  unit-tests:
    name: "Unit Tests"
    uses: ./.github/workflows/test-unit.yml
    secrets: inherit

  integration-tests:
    name: "Integration Tests"
    uses: ./.github/workflows/test-integration.yml
    secrets: inherit

  live-tests:
    name: "Live Tests"
    if: github.event_name == 'push' && (contains(github.ref, 'refs/heads/main') || contains(github.ref, 'refs/heads/develop'))
    needs: [unit-tests, integration-tests]
    uses: ./.github/workflows/test-live.yml
    secrets: inherit

  code-quality:
    name: "Code Quality"
    uses: ./.github/workflows/quality.yml
    secrets: inherit

  documentation:
    name: "Documentation"
    uses: ./.github/workflows/docs.yml
    secrets: inherit
